# --------------------------------------------------------------------------- #
# common
# --------------------------------------------------------------------------- #
[packages.common]

[packages.common.debian]
provider = "apt"
name = ["eza", "tree", "curl", "python3", "git", "npm"]

[packages.common.arch]
provider = "pacman"
name = ["eza", "tree", "curl", "python3", "git", "npm"]

# --------------------------------------------------------------------------- #
# zsh
# --------------------------------------------------------------------------- #
[packages.zsh]
command = "zsh"

[packages.zsh.debian]
provider = "apt"
name = "zsh"

[packages.zsh.arch]
provider = "pacman"
name = "zsh"

[[packages.zsh.config]]
source = "config/zsh/.zshenv"
destination = "~/.zshenv"

[[packages.zsh.config]]
source = "config/zsh/config"
destination = "~/.config/zsh"

# --------------------------------------------------------------------------- #
# tmux
# --------------------------------------------------------------------------- #
[packages.tmux]
command = "tmux"

[packages.tmux.debian]
provider = "apt"
name = "tmux"

[packages.tmux.arch]
provider = "pacman"
name = "tmux"

[[packages.tmux.config]]
source = "config/tmux/config"
destination = "~/.config/tmux"


[[packages.tmux.config]]
source = "config/tmux/plugins/tpm"
destination = "~/.tmux/plugins/tpm"

# --------------------------------------------------------------------------- #
# verible
# --------------------------------------------------------------------------- #
[packages.verible]
command = "verible"
name = "verible"

[packages.verible.debian]
provider = "github"
repo = "chipsalliance/verible"
type = "archive"
binary_dir = "bin"

[packages.verible.debian.assets.arm64]
name = "verible-.*-linux-static-arm64.tar.gz"

# --------------------------------------------------------------------------- #
# oss-cad suite
# --------------------------------------------------------------------------- #
[packages.oss-cad-suite]
name = "oss-cad-suite"

[packages.oss-cad-suite.debian]
provider = "github"
repo = "YosysHQ/oss-cad-suite-build"
type = "archive"

[packages.oss-cad-suite.debian.assets.arm64]
name = "oss-cad-suite-linux-arm64-.*.tgz"
