# --------------------------------------------------------------------------- #
# common
# --------------------------------------------------------------------------- #
[packages.common]

[packages.common.debian]
provider = "apt"
name = ["build-essential", "man", "eza"]

# --------------------------------------------------------------------------- #
# zsh
# --------------------------------------------------------------------------- #
[packages.zsh]
command = "zsh"

[packages.zsh.debian]
provider = "apt"
name = "zsh"

[[packages.zsh.config]]
source = "config/zsh/.zshenv"
destination = "~/.zshenv"

[[packages.zsh.config]]
source = "config/zsh/config"
destination = "~/.config/zsh"

# --------------------------------------------------------------------------- #
# verible
# --------------------------------------------------------------------------- #
[packages.verible]
command = "verible"
name = "verible"

[packages.verible.debian]
provider = "github"
repo = "chipsalliance/verible"
type = "archive"
binary_dir = "bin"

[packages.verible.debian.assets.arm64]
name = "verible-.*-linux-static-arm64.tar.gz"

# --------------------------------------------------------------------------- #
# oss-cad suite
# --------------------------------------------------------------------------- #
[packages.oss-cad-suite]
name = "oss-cad-suite"

[packages.oss-cad-suite.debian]
provider = "github"
repo = "YosysHQ/oss-cad-suite-build"
type = "archive"

[packages.oss-cad-suite.debian.assets.arm64]
name = "oss-cad-suite-linux-arm64-.*.tgz"
