#!/usr/bin/env python3

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import platform
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Any
import re

try:
    import tomllib
except ModuleNotFoundError:
    print("error: Python 3.11+ is required", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "packages.toml"

LOCAL_BIN = Path.home() / ".local" / "bin"
LOCAL_OPT = Path.home() / ".local" / "opt"

PKG_VERSION = "0.1.0"


# ---------------------------------------------------------------------------
# Colors / terminal output
# ---------------------------------------------------------------------------

class Colors:
    RESET = "\033[0m"

    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[34m"
    MAGENTA = "\033[35m"
    CYAN = "\033[36m"

    BOLD = "\033[1m"
    DIM = "\033[2m"

    @classmethod
    def enabled(cls) -> bool:
        """
        Return whether ANSI colors should be used.

        Colors are disabled when:
          - stdout is not a terminal
          - NO_COLOR is set
          - TERM=dumb
        """

        return (
            sys.stdout.isatty()
            and "NO_COLOR" not in os.environ
            and os.environ.get("TERM") != "dumb"
        )

    @classmethod
    def wrap(
        cls,
        text: str,
        color: str,
    ) -> str:
        """Wrap text in an ANSI color when colors are enabled."""

        if not cls.enabled():
            return text

        return f"{color}{text}{cls.RESET}"


def pkg_print(
    message: str = "",
    *,
    color: str = Colors.CYAN,
    bold: bool = False,
) -> None:
    """
    Print output generated by pkg itself.

    All pkg-generated output gets a `pkg:` prefix, making it easy
    to distinguish from output produced by apt/pacman/yay.
    """

    if (not message):
        print()
        return

    text = f"pkg: {message}"

    if bold and Colors.enabled():
        text = f"{Colors.BOLD}{text}{Colors.RESET}"

    if color:
        text = Colors.wrap(text, color)

    print(text)


def pkg_error(message: str) -> None:
    """Print an error generated by pkg."""

    text = f"pkg: error: {message}"

    if Colors.enabled():
        text = Colors.wrap(text, Colors.RED)

    print(text, file=sys.stderr)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def run(
    cmd: list[str],
    *,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    """
    Run a Linux command.

    The command itself is printed by pkg in blue, while the command's
    stdout/stderr remain untouched so apt/pacman/yay retain their own
    normal terminal output.
    """

    pkg_print(
        f"$ {' '.join(cmd)}",
        color=Colors.BLUE,
        bold=True,
    )

    return subprocess.run(
        cmd,
        check=check,
        text=True,
    )


def command_exists(command: str) -> bool:
    """Return True if command is available in PATH."""

    return shutil.which(command) is not None


def command_version(command: str) -> str | None:
    """Try to obtain a command's version string."""

    for args in (["--version"], ["-version"], ["version"]):
        try:
            result = subprocess.run(
                [command, *args],
                capture_output=True,
                text=True,
                check=False,
            )
        except OSError:
            continue

        output = (result.stdout or result.stderr).strip()
        if output:
            return output.splitlines()[0].strip()

    return None


def github_release_version(repo: str) -> str:
    """Return the latest GitHub release tag for a repository."""

    release = github_latest_release(repo)
    tag = release.get("tag_name")

    if not tag:
        raise RuntimeError(
            f"{repo}: GitHub release has no tag_name"
        )

    return str(tag)


def github_installed_version(package_name: str) -> str | None:
    """Return the installed version for a GitHub AppImage package."""

    package_root = LOCAL_OPT / package_name
    current_link = package_root / "current"

    if not current_link.is_symlink():
        return None

    try:
        return current_link.resolve().name
    except OSError:
        return None


def normalize_version(version: str) -> tuple:
    """
    Convert a version-like string into comparable components.

    This intentionally keeps comparison simple and works for common tags
    such as v0.12.5, 0.12.5, and release-0.12.5.
    """

    value = version.strip()

    # Remove a common leading 'v'.
    value = re.sub(r"^[vV]", "", value)

    parts = re.findall(r"\\d+|[A-Za-z]+", value)

    normalized = []
    for part in parts:
        if part.isdigit():
            normalized.append((0, int(part)))
        else:
            normalized.append((1, part.lower()))

    return tuple(normalized)


def versions_differ(installed: str, latest: str) -> bool:
    """Return True when the installed and latest versions differ."""

    return normalize_version(installed) != normalize_version(latest)


def check_apt_package(name: str) -> tuple[str | None, str | None]:
    """
    Return (installed_version, candidate_version) for an apt package.

    The candidate version is the version apt currently knows about.
    """

    installed = subprocess.run(
        ["dpkg-query", "-W", "-f=${Version}", name],
        capture_output=True,
        text=True,
        check=False,
    )

    if installed.returncode != 0:
        return None, None

    installed_version = installed.stdout.strip() or None

    candidate = subprocess.run(
        ["apt-cache", "policy", name],
        capture_output=True,
        text=True,
        check=False,
    )

    candidate_version = None

    for line in candidate.stdout.splitlines():
        if line.strip().startswith("Candidate:"):
            candidate_version = line.split(":", 1)[1].strip()
            break

    return installed_version, candidate_version


def check_pacman_package(name: str) -> tuple[str | None, str | None]:
    """
    Return (installed_version, repository_version) for a pacman package.
    """

    installed = subprocess.run(
        ["pacman", "-Q", name],
        capture_output=True,
        text=True,
        check=False,
    )

    if installed.returncode != 0:
        return None, None

    fields = installed.stdout.strip().split()
    installed_version = fields[1] if len(fields) >= 2 else None

    candidate = subprocess.run(
        ["pacman", "-Si", name],
        capture_output=True,
        text=True,
        check=False,
    )

    candidate_version = None

    for line in candidate.stdout.splitlines():
        if line.strip().startswith("Version"):
            candidate_version = line.split(":", 1)[1].strip()
            break

    return installed_version, candidate_version


def load_manifest() -> dict[str, Any]:
    """Load packages.toml."""

    if not MANIFEST.exists():
        raise RuntimeError(
            f"Package manifest not found: {MANIFEST}"
        )

    with MANIFEST.open("rb") as f:
        return tomllib.load(f)


# ---------------------------------------------------------------------------
# Platform detection
# ---------------------------------------------------------------------------

def detect_distro() -> str:
    """
    Detect the Linux distribution.

    Currently supported:

        Debian/Ubuntu -> debian
        Arch         -> arch
    """

    os_release = Path("/etc/os-release")

    if not os_release.exists():
        raise RuntimeError(
            "Cannot find /etc/os-release"
        )

    values: dict[str, str] = {}

    for line in os_release.read_text().splitlines():
        if "=" not in line:
            continue

        key, value = line.split("=", 1)
        values[key] = value.strip('"')

    distro = values.get("ID")

    if distro in {"debian", "ubuntu"}:
        return "debian"

    if distro == "arch":
        return "arch"

    raise RuntimeError(
        f"Unsupported Linux distribution: {distro}"
    )


def detect_arch() -> str:
    """
    Normalize the machine architecture name to the names used
    by packages.toml.
    """

    machine = platform.machine().lower()

    mapping = {
        "x86_64": "x86_64",
        "amd64": "x86_64",

        "aarch64": "arm64",
        "arm64": "arm64",

        "armv7l": "armv7",
        "armv7": "armv7",
    }

    try:
        return mapping[machine]
    except KeyError:
        raise RuntimeError(
            f"Unsupported architecture: {machine}"
        )


# ---------------------------------------------------------------------------
# GitHub
# ---------------------------------------------------------------------------

def github_latest_release(repo: str) -> dict[str, Any]:
    """
    Fetch the latest GitHub release for a repository.

    Example:
        neovim/neovim
    """

    url = (
        f"https://api.github.com/repos/"
        f"{repo}/releases/latest"
    )

    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "dotfiles-pkg",
        },
    )

    try:
        with urllib.request.urlopen(request) as response:
            data = response.read()

    except Exception as exc:
        raise RuntimeError(
            f"Failed to query GitHub release for {repo}: {exc}"
        ) from exc

    try:
        return json.loads(data)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Invalid JSON returned by GitHub for {repo}"
        ) from exc


def github_find_asset(
    release: dict[str, Any],
    pattern: str,
) -> dict[str, Any]:
    """
    Find a release asset matching a shell-style glob.

    Example:

        nvim-linux-*.appimage
    """

    assets = release.get("assets", [])

    for asset in assets:
        name = asset.get("name")

        if name and fnmatch.fnmatch(name, pattern):
            return asset

    raise RuntimeError(
        f"No GitHub release asset matching {pattern!r} "
        f"was found"
    )


def download_file(
    url: str,
    destination: Path,
) -> None:
    """Download a URL to a local file."""

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    pkg_print(
        f"Downloading {url}",
        color=Colors.YELLOW,
    )

    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "dotfiles-pkg",
        },
    )

    try:
        with urllib.request.urlopen(request) as response:
            with destination.open("wb") as f:
                shutil.copyfileobj(response, f)

    except Exception as exc:
        if destination.exists():
            destination.unlink()

        raise RuntimeError(
            f"Failed to download {url}: {exc}"
        ) from exc


# ---------------------------------------------------------------------------
# Providers
# ---------------------------------------------------------------------------

def package_names(config: dict[str, Any]) -> list[str]:
    """Return package names as a normalized list."""

    names = config.get("name")

    if isinstance(names, str):
        return [names]

    if isinstance(names, list) and all(
        isinstance(name, str) and name for name in names
    ):
        return names

    raise RuntimeError(
        "'name' must be a string or a non-empty list of strings"
    )


def install_apt(
    config: dict[str, Any],
) -> None:
    """Install one or more Debian packages using apt."""

    names = package_names(config)

    run([
        "sudo",
        "apt-get",
        "install",
        "-y",
        *names,
    ])


def install_pacman(
    config: dict[str, Any],
) -> None:
    """Install one or more Arch packages using pacman."""

    names = package_names(config)

    run([
        "sudo",
        "pacman",
        "-S",
        "--needed",
        "--noconfirm",
        *names,
    ])


def install_aur(
    config: dict[str, Any],
) -> None:
    """Install one or more AUR packages using yay."""

    names = package_names(config)

    if not command_exists("yay"):
        raise RuntimeError(
            "AUR provider requires 'yay', "
            "but yay is not installed"
        )

    run([
        "yay",
        "-S",
        "--needed",
        "--noconfirm",
        *names,
    ])


def install_github_appimage(
    package_name: str,
    command: str,
    config: dict[str, Any],
    arch: str,
) -> None:
    """
    Install a GitHub AppImage.

    Layout:

        ~/.local/opt/<package>/<version>/<binary>

        ~/.local/opt/<package>/current
            -> <version>

        ~/.local/bin/<command>
            -> ~/.local/opt/<package>/current/<binary>
    """

    repo = config["repo"]
    assets = config["assets"]

    if arch not in assets:
        raise RuntimeError(
            f"{package_name}: no GitHub asset "
            f"configured for architecture {arch!r}"
        )

    asset_config = assets[arch]

    asset_pattern = asset_config["name"]
    binary_name = asset_config.get(
        "binary",
        command,
    )

    # ------------------------------------------------------------------
    # Query GitHub
    # ------------------------------------------------------------------

    pkg_print(
        f"Checking GitHub release: {repo}",
        color=Colors.YELLOW,
    )

    release = github_latest_release(repo)

    tag = release.get("tag_name")

    if not tag:
        raise RuntimeError(
            f"{package_name}: GitHub release has no tag_name"
        )

    asset = github_find_asset(
        release,
        asset_pattern,
    )

    asset_name = asset["name"]
    download_url = asset["browser_download_url"]

    pkg_print(
        f"{package_name}: "
        f"latest release = {tag}, "
        f"asset = {asset_name}",
        color=Colors.YELLOW,
    )

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------

    package_root = LOCAL_OPT / package_name
    version_root = package_root / tag

    current_link = package_root / "current"

    executable = version_root / binary_name
    command_link = LOCAL_BIN / command

    LOCAL_BIN.mkdir(
        parents=True,
        exist_ok=True,
    )

    package_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ------------------------------------------------------------------
    # Download
    # ------------------------------------------------------------------

    if not executable.exists():
        version_root.mkdir(
            parents=True,
            exist_ok=True,
        )

        download_path = version_root / asset_name

        if not download_path.exists():
            download_file(
                download_url,
                download_path,
            )

        # The AppImage itself is the executable.
        #
        # We rename it to the logical command name so:
        #
        #   ~/.local/opt/neovim/v0.12.5/nvim
        #
        # is used instead of:
        #
        #   ~/.local/opt/neovim/v0.12.5/nvim-linux-arm64.appimage
        if download_path != executable:
            download_path.rename(executable)

        # Ensure executable permission is present.
        executable.chmod(
            executable.stat().st_mode | 0o111
        )

        pkg_print(
            f"Installed {package_name} {tag}",
            color=Colors.GREEN,
            bold=True,
        )

    else:
        pkg_print(
            f"{package_name} {tag} is already installed",
            color=Colors.GREEN,
        )

    # ------------------------------------------------------------------
    # Update "current" symlink
    # ------------------------------------------------------------------

    if current_link.exists() or current_link.is_symlink():
        if not current_link.is_symlink():
            raise RuntimeError(
                f"Refusing to replace non-symlink: "
                f"{current_link}"
            )

        current_link.unlink()

    current_link.symlink_to(tag)

    # ------------------------------------------------------------------
    # Update ~/.local/bin/<command>
    # ------------------------------------------------------------------

    if command_link.exists() or command_link.is_symlink():
        if not command_link.is_symlink():
            raise RuntimeError(
                f"Refusing to replace non-symlink: "
                f"{command_link}"
            )

        command_link.unlink()

    command_link.symlink_to(
        current_link / binary_name
    )

    pkg_print(
        f"Linked {command_link} -> "
        f"{command_link.resolve()}",
        color=Colors.GREEN,
    )


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def expand_path(path: str | Path) -> Path:
    """Expand ~ and environment variables in a path."""

    return Path(os.path.expandvars(str(path))).expanduser()


def config_source_path(source: str) -> Path:
    """Resolve a configuration source relative to the repository root."""

    path = expand_path(source)

    if path.is_absolute():
        return path

    return ROOT / path


def configure_package(
    package_name: str,
    package: dict[str, Any],
) -> None:
    """Install one or more configuration entries for a package."""
    config = package.get("config")

    if config is None:
        return

    # [packages.foo.config] -> dict
    # [[packages.foo.config]] -> list of dicts
    if isinstance(config, dict):
        configs = [config]
    elif isinstance(config, list):
        configs = config
    else:
        raise RuntimeError(
            f"{package_name}: config must be a table or array of tables"
        )

    pkg_print(
        f"Configuring {package_name}",
        color=Colors.MAGENTA,
        bold=True,
    )

    for entry in configs:
        if not isinstance(entry, dict):
            raise RuntimeError(
                f"{package_name}: each config entry must be a table"
            )

        source = entry.get("source")
        destination = entry.get("destination")
        mode = entry.get("mode", "link")

        if not source or not destination:
            raise RuntimeError(
                f"{package_name}: config requires 'source' and 'destination'"
            )

        if mode not in {"link", "contents"}:
            raise RuntimeError(
                f"{package_name}: unsupported config mode {mode!r}; "
                "expected 'link' or 'contents'"
            )

        source_path = config_source_path(source)
        destination_path = expand_path(destination)

        if not source_path.exists():
            raise RuntimeError(
                f"{package_name}: configuration source does not exist: "
                f"{source_path}"
            )

        if mode == "contents" and not source_path.is_dir():
            raise RuntimeError(
                f"{package_name}: config source must be a directory "
                f"when mode='contents': {source_path}"
            )

        if mode == "link":
            _link_config_path(package_name, source_path, destination_path)
            continue

        destination_path.mkdir(parents=True, exist_ok=True)

        for item in sorted(source_path.iterdir()):
            _link_config_path(
                package_name,
                item,
                destination_path / item.name,
            )

def _link_config_path(
    package_name: str,
    source_path: Path,
    destination_path: Path,
) -> None:
    """Safely create a symlink from destination to source."""

    source_resolved = source_path.resolve()

    if destination_path.is_symlink():
        try:
            if destination_path.resolve() == source_resolved:
                pkg_print(
                    f"Config already linked: "
                    f"{destination_path} -> {source_path}",
                    color=Colors.GREEN,
                )
                return
        except OSError:
            pass

        pkg_print(
            f"Replacing existing symlink: {destination_path}",
            color=Colors.YELLOW,
        )
        destination_path.unlink()

    elif destination_path.exists():
        raise RuntimeError(
            f"{package_name}: refusing to replace existing "
            f"file or directory: {destination_path}"
        )

    destination_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    destination_path.symlink_to(source_resolved)

    pkg_print(
        f"Linked {destination_path} -> {source_path}",
        color=Colors.GREEN,
    )


# ---------------------------------------------------------------------------
# Package installation
# ---------------------------------------------------------------------------

def install_package(
    package_name: str,
    package: dict[str, Any],
    distro: str,
) -> None:
    """Install one logical package."""

    config = package.get(distro)

    if config is None:
        raise RuntimeError(
            f"{package_name}: "
            f"no configuration for distro {distro!r}"
        )

    provider = config.get("provider")

    if not provider:
        raise RuntimeError(
            f"{package_name}: provider is missing "
            f"for distro {distro!r}"
        )

    pkg_print()
    pkg_print(
        f"==> {package_name} "
        f"[{distro}/{provider}]",
        color=Colors.MAGENTA,
        bold=True,
    )

    if provider == "apt":
        install_apt(config)

    elif provider == "pacman":
        install_pacman(config)

    elif provider == "aur":
        install_aur(config)

    elif provider == "github":
        github_type = config.get("type")

        if github_type == "appimage":
            install_github_appimage(
                package_name=package_name,
                command=package["command"],
                config=config,
                arch=detect_arch(),
            )

        else:
            raise RuntimeError(
                f"{package_name}: "
                f"unsupported GitHub type "
                f"{github_type!r}"
            )

    else:
        raise RuntimeError(
            f"{package_name}: "
            f"unknown provider {provider!r}"
        )


# ---------------------------------------------------------------------------
# Check
# ---------------------------------------------------------------------------

def check_packages(
    packages: dict[str, Any],
    distro: str,
) -> bool:
    """
    Check package installation state and available versions.

    Returns True if every configured package is installed. Version lookup
    failures do not by themselves make the check fail.
    """

    success = True

    pkg_print()
    pkg_print(
        f"{'Package':<20} {'Installed':<24} {'Available':<24} Status",
        color=Colors.BOLD,
    )
    pkg_print(
        f"{'-' * 20} {'-' * 24} {'-' * 24} {'-' * 12}",
        color=Colors.DIM,
    )

    for name, package in packages.items():
        command = package.get("command")
        config = package.get(distro, {})
        provider = config.get("provider")

        # A command-based package (e.g. a GitHub AppImage) is checked via
        # its executable. OS package groups are checked package-by-package.
        if command:
            if not command_exists(command):
                pkg_print(
                    f"{name:<20} {'not installed':<24} {'-':<24} "
                    f"{'[MISSING]'}",
                    color=Colors.RED,
                )
                success = False
                continue

            installed_version = None
            available_version = None

            try:
                if provider == "github" and config.get("type") == "appimage":
                    installed_version = github_installed_version(name)
                    available_version = github_release_version(
                        config["repo"]
                    )
                elif provider == "apt":
                    names = package_names(config)
                    if len(names) == 1:
                        installed_version, available_version = check_apt_package(
                            names[0]
                        )
                elif provider in {"pacman", "aur"}:
                    names = package_names(config)
                    if len(names) == 1:
                        installed_version, available_version = check_pacman_package(
                            names[0]
                        )

                if installed_version is None:
                    installed_version = command_version(command)

            except Exception as exc:
                pkg_print(
                    f"{name}: version check failed: {exc}",
                    color=Colors.YELLOW,
                )

            installed_display = installed_version or "unknown"
            available_display = available_version or "unknown"

            if (
                installed_version
                and available_version
                and versions_differ(installed_version, available_version)
            ):
                status = "[UPDATE]"
                color = Colors.YELLOW
            else:
                status = "[ OK ]"
                color = Colors.GREEN

            pkg_print(
                f"{name:<20} {installed_display:<24} "
                f"{available_display:<24} {status}",
                color=color,
            )
            continue

        # Grouped OS packages have no single command. Check each package.
        try:
            names = package_names(config)
        except Exception as exc:
            pkg_print(
                f"{name}: package check failed: {exc}",
                color=Colors.RED,
            )
            success = False
            continue

        for package_name in names:
            installed_version = None
            available_version = None

            try:
                if provider == "apt":
                    installed_version, available_version = check_apt_package(
                        package_name
                    )
                elif provider in {"pacman", "aur"}:
                    installed_version, available_version = check_pacman_package(
                        package_name
                    )
                else:
                    raise RuntimeError(
                        f"unsupported provider {provider!r}"
                    )
            except Exception as exc:
                pkg_print(
                    f"{name}/{package_name}: version check failed: {exc}",
                    color=Colors.YELLOW,
                )

            if installed_version is None:
                pkg_print(
                    f"{name}/{package_name:<15} "
                    f"{'not installed':<24} {'-':<24} [MISSING]",
                    color=Colors.RED,
                )
                success = False
                continue

            installed_display = installed_version
            available_display = available_version or "unknown"

            if (
                available_version
                and versions_differ(installed_version, available_version)
            ):
                status = "[UPDATE]"
                color = Colors.YELLOW
            else:
                status = "[ OK ]"
                color = Colors.GREEN

            pkg_print(
                f"{name}/{package_name:<15} "
                f"{installed_display:<24} "
                f"{available_display:<24} {status}",
                color=color,
            )

    pkg_print()
    return success


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="pkg",
        description=(
            "Cross-distro package manager "
            "for dotfiles"
        ),
    )

    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {PKG_VERSION}",
    )

    subparsers = parser.add_subparsers(
        dest="action",
        required=True,
    )

    # ------------------------------------------------------------------
    # install
    # ------------------------------------------------------------------

    install_parser = subparsers.add_parser(
        "install",
        help="Install packages",
    )

    install_parser.add_argument(
        "packages",
        nargs="*",
        help=(
            "Packages to install. "
            "If omitted, install everything."
        ),
    )

    # ------------------------------------------------------------------
    # check
    # ------------------------------------------------------------------

    subparsers.add_parser(
        "check",
        help="Check installed packages",
    )

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    manifest = load_manifest()
    packages = manifest.get("packages")

    if not isinstance(packages, dict):
        raise RuntimeError(
            "packages.toml does not contain "
            "a [packages.*] section"
        )

    distro = detect_distro()
    arch = detect_arch()

    pkg_print(
        f"Distribution : {distro}",
        color=Colors.CYAN,
    )

    pkg_print(
        f"Architecture : {arch}",
        color=Colors.CYAN,
    )

    # ------------------------------------------------------------------
    # check
    # ------------------------------------------------------------------

    if args.action == "check":
        pkg_print(
            f"pkg version    : {PKG_VERSION}",
            color=Colors.CYAN,
        )
        return 0 if check_packages(packages, distro) else 1

    # ------------------------------------------------------------------
    # install
    # ------------------------------------------------------------------

    if args.action == "install":
        requested = args.packages

        if requested:
            names = requested
        else:
            names = list(packages.keys())

        for name in names:
            if name not in packages:
                raise RuntimeError(
                    f"Unknown package: {name}"
                )

            install_package(
                package_name=name,
                package=packages[name],
                distro=distro,
            )

            configure_package(
                package_name=name,
                package=packages[name],
            )

        pkg_print()
        pkg_print(
            "Installation complete",
            color=Colors.GREEN,
            bold=True,
        )

        return 0

    raise RuntimeError(
        f"Unknown action: {args.action}"
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    try:
        sys.exit(main())

    except KeyboardInterrupt:
        pkg_print(
            "Interrupted",
            color=Colors.YELLOW,
        )
        sys.exit(130)

    except subprocess.CalledProcessError as exc:
        pkg_error(
            f"command failed with exit code {exc.returncode}"
        )
        sys.exit(exc.returncode)

    except Exception as exc:
        pkg_error(str(exc))
        sys.exit(1)
